export const BASE_URL = "https://www.myinstants.com"
export const READ_ALL_URL = BASE_URL + "/pt/index/br/"
export const SEARCH_URL = BASE_URL + "/search/"
export const RECENTS_URL = BASE_URL + "/en/recents/"
export const CATEGORIES_URL = BASE_URL + "/pt/index/br/"
export const CATEGORIES_INSTANTS_READ_ALL_URL = BASE_URL + "/pt/categories/"
